/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeaRouteImport } from './routes/bea'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizSlugRouteImport } from './routes/quiz.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaRoute = BeaRouteImport.update({
  id: '/bea',
  path: '/bea',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSlugRoute = QuizSlugRouteImport.update({
  id: '/quiz/$slug',
  path: '/quiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bea': typeof BeaRoute
  '/disclaimer': typeof DisclaimerRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bea': typeof BeaRoute
  '/disclaimer': typeof DisclaimerRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bea': typeof BeaRoute
  '/disclaimer': typeof DisclaimerRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bea' | '/disclaimer' | '/quiz/$slug' | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bea' | '/disclaimer' | '/quiz/$slug' | '/quiz'
  id: '__root__' | '/' | '/bea' | '/disclaimer' | '/quiz/$slug' | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeaRoute: typeof BeaRoute
  DisclaimerRoute: typeof DisclaimerRoute
  QuizSlugRoute: typeof QuizSlugRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bea': {
      id: '/bea'
      path: '/bea'
      fullPath: '/bea'
      preLoaderRoute: typeof BeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$slug': {
      id: '/quiz/$slug'
      path: '/quiz/$slug'
      fullPath: '/quiz/$slug'
      preLoaderRoute: typeof QuizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeaRoute: BeaRoute,
  DisclaimerRoute: DisclaimerRoute,
  QuizSlugRoute: QuizSlugRoute,
  QuizIndexRoute: QuizIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
